### ISSUE TITLE
An làm câu 3 bài 7 và câu 1 bài 8

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#12]
câu 3 hệ điều hành mở là gì ? so sánh giữa ưu, nhược điểm giữa hệ điều hành mở và đóng
câu 1 hãy kể 1 số ứng dụng của tin học. nêu ứng dụng nổi bật yêu thích nhất, giải thích

**Comment by Lytanan01pn** [comment]
Câu 3:
Mở điều hành là một phần mềm dùng để điều hành, quản lý toàn bộ tất cả thành phần (bao gồm cả phần cứng và phần mềm) của thiết bị điện tử.
So sánh 
Ưu 
-Tiện lợi 
- giá thành hợp lí
-phù hợp với mọi người
Nhược
-lỗi hệ thống 
-virus có thể xâm nhập
Câu 1:
-photomath
-dicamon
-vietjack
-quanda
Nổi bật là quanda .Vì giúp cho chúng ta giải các bài tập khó nêu ra các dạng bài tập mới giúp chúng ta nâng cao được kĩ năng
