### ISSUE TITLE
Bình làm câu 2 bài 8

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#13]
câu 2 có lĩnh vực nào  mà tin học khó có thể sử dụng

**Comment by BinhDoanphunhuan** [comment]
- Khám chữa bệnh: Tin học hay cụ thể là trí tuệ nhân tạo vẫn chưa thể thay thế đội ngũ y bác sỹ trong việc khám bệnh cho con người

- Tâm lí con người: Cảm xúc của con người rất phức tạp và máy móc chưa thể đủ dữ liệu để phân tích trạng thái tình cảm.
