### ISSUE TITLE
An câu 1

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#15]
Câu 1: Hãy nêu sự ứng dụng tin học của bản thân cho việc học, làm việc trong cuộc sống (nếu làm nhóm, mỗi thành viên nêu ra).

**Comment by Lytanan01pn** [comment]
Zoom
GG meet
MS Team 
Zalo
Join.me
Skype
Google hang out
Go to meeting
AnyMeeting
On24
