### ISSUE TITLE
Phú câu 2

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#16]
Câu 2: Trong thời đại công nghệ phát triển, cập nhật thay đổi liên tục; liệu những xu hướng sử dụng công nghệ hiện tại có phù hợp tất cả với suy nghĩ, sự vận hành của xã hội? Hãy nêu 5 ví dụ và từ đó nói ra suy nghĩ bản thân, có nên giữ nguyên hay thay đổi chúng?

**Comment by phudangphunhuan** [comment]
Theo em thì những xu hướng sử dụng hiện tại có phù hợp với suy nghĩ và sự vận hành của xã hội.
Ví dụ
Trí tuệ nhân tạo (AI)
Công nghệ chuỗi khối (Blockchain)
Internet vạn vật (IoT)
Mạng 5G
Tự động hóa quy trình bằng robot (RPA)
Vì vậy, theo em nên giữ nguyên chúng.
