### ISSUE TITLE
Bình câu 3

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#17]
Câu 3: Thông tin của bản thân có quan trọng không? Hãy “vẽ” ra những tình huống thông tin cá nhân bị kẻ xấu sử dụng và cách khắc phục, bảo vệ.

**Comment by BinhDoanphunhuan** [comment]
Theo em thông tin của bản thân rất quan trọng vì đó là tài sản riêng của chúng ta
 Những thông tin cá nhân bị kẻ xấu sử dụng: 
    + Tài khoảng ngân hàng
    + Địa chỉ nhà, địa chỉ email
    + Tài khoản mật khẩu mxh, số điện thoại
 Cách khắc phục bảo vệ
    + Mỗi người phải có trách nhiệm tự bảo vệ thông tin cá nhân và tự chịu trách nhiệm khi cung cấp những thông tin đó 
    + Không nên chia sẻ thông tin cá nhân trên phương tiện truyền thông xã hội. 
    + Sử dụng mật khẩu mạnh và độc đáo, mọi thứ cần phải được bảo vệ bằng mật khẩu, từ điện thoại di động đến máy tính xách tay của cá nhân nào đó. 
    + Tránh sử dụng Wifi công cộng và tại các điểm nóng, việc sử dụng kết nối Wifi tại các sân bay, nhà ga, trạm xe buýt và quán cà phê có vẻ hấp dẫn.
