### ISSUE TITLE
Thịnh câu 1,2 bài 10

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#18]
Câu 1: Hệ điều hành là gì? Phân biệt các loại hệ điều hành 

Câu 2: Hệ điều hành thường được lưu trữ ở đâu? Vì sao phải nạp hệ điều hành vào máy tính thì máy mới hoạt động được?

**Comment by DangQuocTh1nh** [comment]
câu 1: 
+Hệ điều hành có ba loại chính sau:

a) Đơn nhiệm một người dùng

- Các chương trình phải được thực hiện lần lượt.

- Mỗi lần làm việc chỉ có một người được đăng kí vào hệ thống.

- Hệ điều hành loại này đơn giản và không đòi hỏi máy tính phải có bộ xử lí mạnh.

- Ví dụ: MS-DOS là một hệ điều hành đơn nhiệm một người dùng.

b) Đa nhiệm một người dùng

- Chỉ cho phép một người được đăng kí vào hệ thống nhưng có thể kích hoạt cho hệ thống thực hiện đồng thời nhiều chương trình.

- Hệ điều hành loại này khá phức tạp và đòi hỏi máy phải có bộ xử lí đủ mạnh.

- Ví dụ: Windows 95 là hệ điều hành đa nhiệm một người dùng.

c) Đa nhiệm nhiều người dùng

- Cho phép nhiều người được đăng kí vào hệ thống, có thể thực hiện đồng thời nhiều chương trình.

- Hệ điều hành loại này rất phức tạp, đòi hỏi máy phải có bộ xử lí mạnh, bộ nhớ trong lớn và thiết bị ngoại vi phong phú.

- Ví dụ: Window's XP là một hệ điều hành đa nhiệm nhiều người dùng.
+Hệ điều hành (tiếng Anh: Operating System - viết tắt: OS) là một phần mềm dùng để điều hành, quản lý toàn bộ tất cả thành phần (bao gồm cả phần cứng và phần mềm) của thiết bị điện tử.

Có vai trò trung gian trong việc giao tiếp giữa người sử dụng và thiết bị.

**Comment by DangQuocTh1nh** [comment]
câu 2: +Hệ điều hành được lưu trữ dưới dạng các môđun độc lập trên bộ nhớ ngoài (Đĩa cứng, đĩa mềm, CD...)
+Nếu không cài đặt hệ điều hành trước tiên thì màn hình sẽ không hiển thị bất cứ thứ gì, các thao tác với chuột, bàn phím,... sẽ không mang lại bất kì hiệu ứng nào.
