### ISSUE TITLE
Lý Tấn An trả lời câu hỏi 1,2 điiiiii

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#3]
Câu 1: Trong các yêu cầu sau, yêu cầu nào được xem là bài toán: giải phương trình ax2+bx+c=0; In một dòng chữ ra màn hình, tìm ước chung lớn nhất của 2 số nguyên dương a, b; tra cứu một từ trong từ điển; tính diện tích hình tròn? Vậy khái niệm "Bài toán" trong Tin học có khác gì không?Giải thích tại sao? Khi giải một bài toán trên máy tính cần quan tâm đến những yếu tố nào?Hãy nêu ra các yếu tố đó và các ví dụ? 
Câu 2: Theo các em làm thế nào để từ Input của bài toán, máy tính tìm cho ta Output? Các em hãy nhận xét và đưa ra khái niệm thuật toán? Từ khái niệm thuật toán các em 2hãy tìm hiểu và hãy nêu ra các tính chất của thuật toán ? ví dụ?

**Comment by Lytanan01pn** [comment]
Câu 1: 
Khái niệm bài toán trong tin học khác với từ điển.Vì trong phạm vi tin học ,có thể quan niệm bài toán là 1 việc nào đó ta mún máy tính thực hiện.
Ta cần quan tâm đến 2 yếu tố : đưa vào máy thông tin gì(Input)và cần lấy ra thông tin gì (Output).
Ví dụ: ax2 + bx + c = 0 (a ≠ 0).
Input    : Các số thực a,b,c (a ≠ 0)
Output : Số thực x thỏa : ax2+bx+ c = 0

**Comment by Lytanan01pn** [comment]
Câu 2:
Thuật toán để giải 1 bài toán là 1 dãy hữu hạn các thao tác được sắp xếp theo 1 trình tự xác định sao cho sau khi thực hiện dãy thao tác ấy ,từ Input của bài toán , ta nhận được Output cần tìm .
