### ISSUE TITLE
Lời xin lỗi thầy và các bạn

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#33]
Em là Trọng Hiếu, em muốn gửi lời xin lỗi này tới thầy và các bạn vì tuần trước e đã quên k làm project và issue ạ. Mong thầy chiếu cố và bỏ qua cho nhóm e lần này ạ. Em cảm ơn

**Comment by DangQuocTh1nh** [comment]
mốt chừa nhá
