### ISSUE TITLE
Thịnh ( tuần 3 )

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#34]
Sử dụng thành ngữ / tục ngữ / ca dao hay thơ tự sáng tác để bày tỏ quan điểm, nghị luận về cuộc sống xung quanh mà bản thân cảm nhận được ( về sự kiên trì )
• Số lượng thành ngữ / tục ngữ / ca dao và thơ cần sử dụng trong bài làm: 3 (đối với thơ tự
sáng tác cần 2 câu trở lên).

**Comment by DangQuocTh1nh** [comment]
Hữu chí cánh thành


Có chí làm quan, có có gan làm giàu.


Người có chí thì nên, nhà có nền thì vững.
stolen by: https://hoatieu.vn/ca-dao-tuc-ngu-ve-sieng-nang-kien-tri-211451
