### ISSUE TITLE
An ( tuần 3 )

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#35]
Sử dụng thành ngữ / tục ngữ / ca dao hay thơ tự sáng tác để bày tỏ quan điểm, nghị luận về cuộc sống xung quanh mà bản thân cảm nhận được ( về tình bạn )
• Số lượng thành ngữ / tục ngữ / ca dao và thơ cần sử dụng trong bài làm: 3 (đối với thơ tự
sáng tác cần 2 câu trở lên).

**Comment by Lytanan01pn** [comment]
1.Đã là bạn thì mãi mãi là bạn,
Đừng như sông lúc cạn lúc đầy.

2.Học thầy không tày học bạn.

3.Bạn bè ít thôi vừa đủ dùng
Chứ đừng để cả thùng
Rồi lâm vào đường cùng
Phút cuối cùng nó mới đi cúng.

**Comment by Lytanan01pn** [comment]
https://www.google.com/amp/s/meta.vn/amp/hotro/nhung-cau-ca-dao-tuc-ngu-noi-ve-tinh-ban-dep-trong-sang-lanh-manh-11361

https://www.google.com/amp/s/amp.voh.com.vn/song-dep/30-cau-ca-dao-tuc-ngu-ve-tinh-ban-moi-quan-he-can-co-cua-moi-con-nguoi-378977.html
