### ISSUE TITLE
Phú ( tuần 3 )

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#36]
Sử dụng thành ngữ / tục ngữ / ca dao hay thơ tự sáng tác để bày tỏ quan điểm, nghị luận về cuộc sống xung quanh mà bản thân cảm nhận được ( về sự dũng cảm )
• Số lượng thành ngữ / tục ngữ / ca dao và thơ cần sử dụng trong bài làm: 3 (đối với thơ tự
sáng tác cần 2 câu trở lên).

**Comment by phudangphunhuan** [comment]
Giặc đến nhà, đàn bà cũng phải đánh.
Không vào hang hổ sao bắt được hổ.
Lửa thử vàng gian nan thử sức.
Nguồn:
https://www.google.com/amp/s/amp.voh.com.vn/song-dep/16-cau-tuc-ngu-noi-ve-long-dung-cam-nang-cao-gia-tri-con-nguoi-378680.html
