### ISSUE TITLE
Bình ( tuần 3 )

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#37]
Sử dụng thành ngữ / tục ngữ / ca dao hay thơ tự sáng tác để bày tỏ quan điểm, nghị luận về cuộc sống xung quanh mà bản thân cảm nhận được ( về sự bao dung )
• Số lượng thành ngữ / tục ngữ / ca dao và thơ cần sử dụng trong bài làm: 3 (đối với thơ tự
sáng tác cần 2 câu trở lên).

**Comment by BinhDoanphunhuan** [comment]
1. Đánh kẻ chạy đi, không ai đánh người chạy lại.

2. Mình vì mọi người, mọi người vì mình.

3. Bàn tay có ngón ngắn ngón dài.
[Nguồn: ](https://www.google.com/amp/s/meta.vn/amp/hotro/ca-dao-tuc-ngu-ve-long-khoan-dung-12955)

**Comment by BinhDoanphunhuan** [comment]
1.Đánh kẻ chạy đi, không ai đánh người chạy lại.

2. Mình vì mọi người, mọi người vì mình.

3. Bàn tay có ngón ngắn ngón dài
.Nguồn: https://www.google.com/amp/s/meta.vn/amp/hotro/ca-dao-tuc-ngu-ve-long-khoan-dung-12955
