### ISSUE TITLE
Phú ơi làm deadline nèeeeee

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#4]
Câu 3: Bài toán: vẽ hình tam giác vuông lên bảng.Thuật toán nào được xem là thuật toán giải bài toán? Tại sao? 

Graphical user interface

Description automatically generated 

Câu 4: Có mấy cách diễn tả thuật toán? Qua ví dụ ở câu 3,các em hãy diễn tả thuật toán của bài toán trên?

**Comment by phudangphunhuan** [comment]
Câu 3:
Thuật toán giải là thuật toán 2.
Vì bài toán chỉ kêu gọi tam giác vuông và chỉ có thuật toán 2 đáp ứng được vì có bước: "nếu tam giác thì kết thúc", thuật toán 1 chỉ kêu là tam giác nên tam giác được vẽ ở thuật toán 1 có thể là tam giác thường, vì thế ta không thể nhân được hình vẽ tam giác.
Câu 4:
Có 2 cách diễn tả thuật: Sử dụng
phương pháp liệt kê Sử dụng
khối bản đồ
A.Dùng phương pháp liệt kê:
Bước 1: Xóa bảng
Bước 2: Vẽ tam giác
Bước 3: Nếu tam giác vuông thì kết thúc
Bước 4 : Quay lại bước 1
B.Dùng sơ đồ khối:
Hình ô văn: start
=> Hình chữ nhật: xóa bảng
=> Hình chữ nhật: vẽ tam giác
=> Hình thoi: tam giác vuông
Nếu sai: quay lại ô"Hình chữ nhật: xóa bảng"
Nếu đúng: thông báo đây là hình tam giác
Hình ô văn: end
