### ISSUE TITLE
Câu 5,6 của Bình

### ISSUE THREAD

**Issue by HIEU10A13stt14** [HIEU10A13stt14/nhom8-10A13#5]
Câu 5: Qua tìm hiểu về bài toán giải phương trình bậc 2: ax2+bx+c=0, Các em hãy tìm Input và Output của bài toán? Các em hãy nêu ý tưởng về việc giải thuật toán trên? 

Câu 6: Có mấy cách để mô tả thuật toán ở câu 5 trên? Các em hãy mô tả thuật toán trên bằng cách liệt kê bước hoặc dùng sơ đồ khối?

**Comment by BinhDoanphunhuan** [comment]
Câu5 
Input: a,b,c (a khác 0)
Output: x1, x2 hoặc vô nghiệm
hoặc x1=x2= 
if(a=0)
Return b/c
if(b=0)
Return c
- Ý tưởng:
- Tính d = b2 - 4ac.
- Lần lượt xét ba trường hợp cho giá trị d:
nếu  d <0 thì pt vô nghiệm
nếu d = 0 thì kết luận phương trình có một nghiệm x =-b/2a
nếu d > 0 thì kết luận phương trình có hai nghiệm phân biệt là:
x - (-b± √ d ) / 2a.
Câu 6
Thuật toán:
Mô tả thuật toán bằng cách liệt kê:
Bước I. Nhập ba số a, b, c;
Bước 2. d 4-(b*b - 4*a*c);
Bước 3.
nếu d < 0 thì đưa ra thông báo phương trình vô nghiệm rồi kết thúc;
nếu d = 0 thì đưa ra thông báo phương trình có một nghiệm và tính nghiệm
x = -b/(2*a), rồi kết thúc;
nếu (d> 0 thì đưa ra thông báo phương trình có hai nghiệm phân biệt, tính nghiệm X/= (-b + -√ d) / (2*a) và x2 = (-b - √ d ) / (2*a), rồi kết thúc;
